#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Oct 05 10:02:16 BST 2026
allowUnknownShaders=false
colorSpace=DCI_P3
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.9.1 + EuphoriaPatches_1.10.1
